using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using PSHostsFile;
using System.IO.IsolatedStorage;
using System.IO;
using System.Text.RegularExpressions;
using System.Collections.ObjectModel;
using System.Xml.Linq;
using System.Windows.Threading;
using System.Runtime.InteropServices;
using System.Windows.Interop;



namespace SocialSilence
{
    /// <summary>
    /// Interaction logic for Page2.xaml
    /// </summary>
    public partial class StartPage : CommonFunctions
    {

        public static int GetWindowLong(IntPtr hWnd, int nIndex)
        {
            if (IntPtr.Size == 4)
            {
                return GetWindowLong32(hWnd, nIndex);
            }
            return GetWindowLongPtr64(hWnd, nIndex);
        }


        [DllImport("user32.dll", EntryPoint = "GetWindowLong", CharSet = CharSet.Auto)]
        private static extern int GetWindowLong32(IntPtr hWnd, int nIndex);

        [DllImport("user32.dll", EntryPoint = "GetWindowLongPtr", CharSet = CharSet.Auto)]
        private static extern int GetWindowLongPtr64(IntPtr hWnd, int nIndex);

        private const int GWL_STYLE = -16;
        bool backUpHost = true;
        ObservableCollection<string> defaultlist = new ObservableCollection<string>();
        MessageBoxResult result;
        List<string> domainsPresent = new List<string>();
        string hostMessage;
        public static int getwindow;

        public StartPage()
        {
            InitializeComponent();
            Loaded += StartPage_Loaded;
                      
        }


        private void StartPage_Loaded(object sender, RoutedEventArgs e)         // On loading the page , create a backup of the host file into application . 
        {
            NavigationWindow win = (NavigationWindow)Window.GetWindow(this);
            var hwnd = new WindowInteropHelper(win).Handle;
            getwindow = GetWindowLong(hwnd, GWL_STYLE);       
            PasswordRequire.notifyIcon.Click += notifyIcon_Click;
            string hostfile_location = PSHostsFile.HostsFile.GetHostsPath();
            FileAttributes hostattributes = File.GetAttributes(hostfile_location);

            if (hostattributes.ToString().Contains(FileAttributes.Hidden.ToString()) || hostattributes.ToString().Contains(FileAttributes.System.ToString()) || hostattributes.ToString().Contains(FileAttributes.ReadOnly.ToString()))
            {
                File.SetAttributes(hostfile_location, FileAttributes.Normal);
            }

            string[] lines = File.ReadAllLines(hostfile_location);
            string matchLine = "#This file is Generated by SocialSilence";
            foreach (string line in lines)                                            //Read the lines in the host file to check if the previous file was created by application. 
            {
                if(Regex.IsMatch(line,matchLine))
                {
                    backUpHost = false;                                               // If the host file was created by application do not make copy .
                    RestoreSetting restoreObj = new RestoreSetting(hostfile_location);
                    restoreObj.ShowsNavigationUI = false;
                    NavigationService.Navigate(restoreObj);
                    break;
                }
            }

           
            if (backUpHost)
            {
                if (System.IO.File.Exists(PasswordRequire.filePath + "host"))                                // Check if the backkup host file exits or not . 
                {
                    FileAttributes hostAttrib = File.GetAttributes(PasswordRequire.filePath + "host");
                    if (hostAttrib.ToString().Contains(FileAttributes.System.ToString()) || hostAttrib.ToString().Contains(FileAttributes.Hidden.ToString()))
                    {
                        File.SetAttributes(PasswordRequire.filePath + "host", FileAttributes.Normal);
                    }
                }
                File.Copy(hostfile_location, PasswordRequire.filePath + "host", true);
                File.SetAttributes(PasswordRequire.filePath + "host", FileAttributes.System | FileAttributes.Hidden);
                
            }
            

        }

        void notifyIcon_Click(object sender, EventArgs e)
        {
            SocialSilence.SysTrayMenu systray = new SysTrayMenu();
            systray.IsOpen = true;

            var _popupTimer = new DispatcherTimer(DispatcherPriority.Normal);
            _popupTimer.Interval = TimeSpan.FromMilliseconds(5000);
            _popupTimer.Tick += (obj, x) =>
            {
                systray.IsOpen = false;
            };
            _popupTimer.Start();
        }


        private void GoWithDefault(object sender, RoutedEventArgs e)
        {
            XElement root = XElement.Load(@"Resources\XMLFile1.xml");

            IEnumerable<string> site = from el in root.Elements("site")
                                       select el.Element("name").Value;

            foreach (string elm in site)
            {
                defaultlist.Add(elm);
            }

            if (File.Exists(PasswordRequire.filePath + "host") && backUpHost)
            {
                hostMessage = (string)this.FindResource("hostMessage");
                File.SetAttributes(PasswordRequire.filePath + "host", FileAttributes.Normal);
                string[] lines = File.ReadAllLines(PasswordRequire.filePath + "host");
                string matchLine = "^www.";
                string matchline2 = ".com$";                  
                foreach (string line in lines)
                {
                    if (Regex.IsMatch(line, matchLine, RegexOptions.IgnoreCase) || Regex.IsMatch(line, matchline2, RegexOptions.IgnoreCase))  // Check the backup host file for domains listed by the user. 
                {
                    result = Xceed.Wpf.Toolkit.MessageBox.Show(hostMessage, "Message", MessageBoxButton.YesNo);
                    break;
                }
                }

                foreach(string line in lines)
                {
                    if(Regex.IsMatch(line,matchLine,RegexOptions.IgnoreCase)|| Regex.IsMatch(line,matchline2,RegexOptions.IgnoreCase))
                    {                        
                        domainsPresent.Add(line);
                    }

                }
                File.SetAttributes(PasswordRequire.filePath + "host", FileAttributes.Hidden | FileAttributes.System);
            }

            AdittionalOptions page = new AdittionalOptions(defaultlist,result,false,domainsPresent);
            NavigationService.Navigate(page);
            page.ShowsNavigationUI = true;

           

        }

        private void GoToCustomizeList(object sender, RoutedEventArgs e)
        {
            NavigationWindow win = (NavigationWindow)Window.GetWindow(this);
            win.RemoveBackEntry();
            CustomizeList CLobj = new CustomizeList(backUpHost);
            this.NavigationService.Navigate(CLobj);
            ShowsNavigationUI = true;
        }

     

        //private void ChangeOpacity(object sender, MouseEventArgs e)
        //{
        //    var button_tri = DefaultSetting.Triggers;
        //}
    }
}
